// =================== REGISTER ====================

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// =================== PROFILE ====================

export const GET_PROFILE = "GET_PROFILE_ID";
// export const CREATE_PROFILE = "CREATE_PROFILE";
export const EDIT_PROFILE = "EDIT_PROFILE";
// export const DELETE_PROFILE = "DELETE_PROFILE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_ALL_PROVINCE = "GET_ALL_PROVINCE";
// export const GET_PROVINCE = "GET_PROVINCE_ID";

export const GET_ALL_CITY = "GET_ALL_CITY";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_ID = "GET_PRODUCT_DETAIL";
export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
export const GET_PRODUCT_BY_USER = "GET_PRODUCT_BY_USER";
export const GET_PRODUCT_BY_USER_WISHLIST = "GET_PRODUCT_BY_USER_WISHLIST";
export const GET_PRODUCT_BY_USER_SOLD = "GET_PRODUCT_BY_USER_SOLD";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const EDIT_PRODUCT = "CREATE_PRODUCT";
export const DRAFT_PRODUCT = "DRAFT_PRODUCT";
export const GET_CATEGORY = "GET_CATEGORY";

export const CREATE_TRANSACTION = "CREATE_TRANSACTION";

export const PUBLISH_PRODUCT = "PUBLISH_PRODUCT";
// export const EDIT_PROFILE = "EDIT_PROFILE";
// export const DELETE_PROFILE = "DELETE_PROFILE";

// =================== TRANSACTION ====================
export const GET_NOTIFICATION_SELLER = "GET_NOTIFICATION_SELLER";
export const GET_NOTIFICATION_SELLER_BY_ID = "GET_NOTIFICATION_SELLER_BY_ID";
export const ACCEPT_OFFER = "ACCEPT_OFFER";
export const REJECT_OFFER = "REJECT_OFFER";
export const GET_NOTIFICATION_BUYER = "GET_NOTIFICATION_BUYER";
